import os
from pathlib import Path

NUM_LATENT_CHANNELS = 4
BATCH_SIZE = 16
IMAGE_SIZE = 256
TEST_SPLIT_RATIO = 0.1

NUM_TUMOR_CLASSES = 7
NUM_LOCATION_CLASSES = 15
NUM_CLASSES = NUM_TUMOR_CLASSES * NUM_LOCATION_CLASSES

VAE_EPOCHS = 100
VAE_LR = 3e-4
VAE_KL_BETA_MAX = 1e-5
VAE_KL_WARMUP_EPOCHS = 10
VAE_LPIPS_WEIGHT = 0.5

UNET_LR = 1e-4
UNET_EPOCHS = 1000
DENOISING_STEPS = 1000
WARMUP_STEPS = 500

DATASET_DIR = os.path.join("data", "dataset")
VAE_IMAGE_DIR = Path(DATASET_DIR) / "entire_final_patched_BTXRD"
UNET_IMAGE_DIR = Path(DATASET_DIR) / "final_patched_BTXRD"
JSON_DIR = Path(DATASET_DIR) / "BTXRD" / "Annotations"
XLSX_PATH = Path(DATASET_DIR) / "BTXRD" / "dataset.xlsx"
